---

- name: Checking if we already have the Redis source code
  stat: path=/root/redis-{{ redis_version }}.tar.gz
  register: get_redis

- name: Downloading Redis
  get_url: url=http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz dest=/root
  when: get_redis.stat.exists == false

- name: Unpacking Redis
  unarchive: dest=/root src=/root/redis-{{ redis_version }}.tar.gz copy=no

- name: Creating etc & var directories for Redis
  file: path={{ item }} owner=root group=root state=directory
  with_items:
    - '/etc/redis'
    - '/var/redis/{{ redis_listen_port }}'

- name: Installing Redis
  command: creates=/usr/local/bin/redis-server chdir=/root/redis-{{ redis_version }} make install

- name: Creating user redis
  user: name=redis system=yes home=/var/lib/redis shell=/bin/false

- name: Setting up the init.d script
  template: src=redis{{ redis_listen_port }}.j2 dest=/etc/init.d/redis{{ redis_listen_port }} mode=0755

- name: Setting up the Redis config
  template: src={{ redis_listen_port }}.conf dest=/etc/redis/{{ redis_listen_port }}.conf

- name: Ensuring Redis is running
  service: name=redis{{ redis_listen_port }} state=started pattern={{ redis_listen_port }} enabled=yes

- name: Enabling Redis to start at boot
  command: /sbin/chkconfig --add redis{{ redis_listen_port }}
