---
- name: installing maintenance and debugging related packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: inst_pkgs

- name: configuring NTP
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp
