---
- name: cloning the repository

  # To clone a specific branch run the playbook with
  # --extra_vars "git_branch=branch-name"
  git: repo={{ repository_url }}
       dest=/vagrant/data_store/magento/
       version={{ git_branch | default('master') }}
       ssh_opts="-o StrictHostKeyChecking=no"

  # It's needed to run this command as a normal user (vagrant, not root)
  # otherwise it wouldn't have the forwarded ssh key to clone the repo
  # inside the VM
  sudo: no

- name: setting up local.xml
  copy: src=local.xml dest=/vagrant/data_store/magento/app/etc/

- name: enabling errors output
  file: src=/vagrant/data_store/magento/errors/local.xml.sample dest=/vagrant/data_store/magento/errors/local.xml        state=link force=yes

- name: installing php5-mysql
  apt: name=php5-mysql state=latest update_cache=yes
  sudo: yes
