---

- hosts: ses:bkn_cache
  sudo: yes
  roles: [ magento/redis ]

- hosts: php
  roles: [ magento/php ]

- hosts: web
  sudo: yes
  roles: [ magento/web ]
  tags: magento-web

- hosts: db
  sudo: yes
  roles: [ magento/db ]
