---
- include: common.yml

- hosts: db
  user: apps
  sudo: yes
  vars:
    opencart_db_user: opencart
    opencart_db_pass: 12345

  pre_tasks:

    - name: checking if the correct vars are defined
      fail:
        msg: |
          You should specify what version of opencart you want to install.
          To do that, run again the command using --extra-vars, for example:

              $ ansible-playbook provisioning/opencart.yml --extra-vars oc_version=1.5.6
      when: oc_version is not defined

    - name: defining the database name to be used by this version
      set_fact:
        oc_database: "{{ 'oc' + oc_version|lower|replace('.', '') }}"
      when: oc_database is not defined

  roles:
    - opencart/db

- hosts: web
  user: apps
  sudo: yes
  pre_tasks:

    - name: defining the version subdomain
      set_fact:
        oc_version_subdomain: "{{ 'oc' + oc_version|lower|replace('.', '') }}"
      when: oc_version_subdomain is not defined

  roles:
    - opencart/php
    - opencart/web
    - vqmod

